# Generated by Django 6.0 on 2026-04-15 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场地名称')),
                ('description', models.TextField(blank=True, verbose_name='场地描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.court', verbose_name='场地')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourtAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('start_time', models.TimeField(verbose_name='每天开始时间')),
                ('end_time', models.TimeField(verbose_name='每天结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='booking.court', verbose_name='场地')),
            ],
            options={
                'verbose_name': '场地可用时间段',
                'verbose_name_plural': '场地可用时间段',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
