# Generated by Django 6.0 on 2026-04-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学员姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('total_class_hours', models.IntegerField(default=0, verbose_name='课时总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to='booking.court', verbose_name='场地')),
            ],
            options={
                'verbose_name': '课程预约',
                'verbose_name_plural': '课程预约',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseBookingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_hours', models.IntegerField(verbose_name='扣除课时数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='booking.coursebooking', verbose_name='课程预约')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to='booking.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '课程学员',
                'verbose_name_plural': '课程学员',
                'unique_together': {('booking', 'student')},
            },
        ),
    ]
