# Generated by Django 6.0 on 2026-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_student_coursebooking_coursebookingstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预约人姓名'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booker_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='预约人联系方式'),
        ),
    ]
