# Generated by Django 6.0 on 2026-05-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_booker_name_booking_booker_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('court', '场地预约'), ('course', '课程预约')], default='court', max_length=20, verbose_name='预约类型'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='BookingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_hours', models.IntegerField(verbose_name='扣除课时数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='booking.booking', verbose_name='预约')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '预约学员',
                'verbose_name_plural': '预约学员',
                'unique_together': {('booking', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursebookingstudent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursebookingstudent',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='coursebookingstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseBooking',
        ),
        migrations.DeleteModel(
            name='CourseBookingStudent',
        ),
    ]
