# Generated by Django 6.0 on 2026-05-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_coursebookingstudent_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='场地类型名称')),
                ('is_default', models.BooleanField(default=False, verbose_name='系统默认类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场地类型',
                'verbose_name_plural': '场地类型',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['court_type__name', 'court_number', 'id'], 'verbose_name': '场地', 'verbose_name_plural': '场地'},
        ),
        migrations.AddField(
            model_name='court',
            name='court_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='场地编号'),
        ),
        migrations.AddField(
            model_name='court',
            name='court_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='booking.courttype', verbose_name='场地类型'),
        ),
    ]
